name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs: # 잡 (Jobs) : 워크플로우에서 실행되는 작업 단위
  build-and-deploy: # 잡 이름
    runs-on: ubuntu-latest

    steps:
      # 1. GitHub 레포지토리 체크아웃
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Docker 이미지 빌드 & 푸시
      - name: Build and Push Docker Image to Docker Hub
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/ktb-be-assignment --platform linux/amd64 .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/ktb-be-assignment

      # 3. EC2 접속 & 어플리케이션 실행
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          port: 22
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/ktb-be-assignment
            cd ~/app
            echo "${{ secrets.APPLICATION_CONFIG }}" > ./config/application-secret.yml
            docker-compose down
            docker-compose up -d